name: Shellcheck

on:
  push:
    paths:
      - '**.sh'
  pull_request:
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up shellcheck
        run: sudo apt-get install shellcheck

      - name: Run shellcheck
        run: find . -type f -iname "*.sh" -exec shellcheck {} \;
